# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.68.0"

default_platform :android

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  lane :bump_version_code do
    path = '../app/build.gradle'
    re = /versionCode\s+(\d+)/ 

    s = File.read(path)
    versionCode = s[re, 1].to_i
    s[re, 1] = (ENV['CI_BUILD_ID'] || (versionCode + 1)).to_s

    f = File.new(path, 'w')
    f.write(s)
    f.close
  end

  lane :fabric do
    # build the release variant
    bump_version_code
    gradle(task: 'assemble', build_type: 'Release')
  
    # upload to Beta by Crashlytics
    crashlytics(
      api_token: "CHANGE_ME",
      build_secret: "CHANGE_ME"
    )
  end

  lane :build_android do
    gradle(task: 'assemble', build_type: 'Release')
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleRelease")
    supply
  end

  lane :icon do
    android_appicon(
      appicon_image_file: '../icon_android.png',
      appicon_icon_types: [:launcher],
      appicon_path: 'app/src/main/res/mipmap'
    )
    android_appicon(
      appicon_image_file: '../icon_android.png',
      appicon_icon_types: [:notification],
      appicon_path: 'app/src/main/res/drawable',
      appicon_filename: 'ic_notification'
    )
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

# More information about multiple platforms in fastlane: https://docs.fastlane.tools/advanced/#control-configuration-by-lane-and-by-platform
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://docs.fastlane.tools/#metrics
